# Generated by Django 2.2.16 on 2022-03-31 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('ac882235-df08-4cf9-8d11-579bd5a9e870'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
