# Generated by Django 2.2.16 on 2022-04-08 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('672ec8bc-421b-4b77-a687-ceb2508980d1'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
