# Generated by Django 2.2.16 on 2022-04-09 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220408_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('ea57dbd1-b21d-4689-9746-78f08137f9a9'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
