# Generated by Django 2.2.16 on 2022-03-31 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220331_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('0e1e3b96-3622-4dad-9012-c82479d12481'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
