# Generated by Django 2.2.16 on 2022-04-09 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220409_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('ecc9e333-4c43-46af-8052-7d076ce01d0e'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
