# Generated by Django 2.2.16 on 2022-04-09 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220409_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('7b8b9778-7734-4d49-bfbc-c656e041971a'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
