# Generated by Django 2.2.16 on 2022-03-31 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220331_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('855edf2c-c7a4-4094-976e-b1c14ed94ba5'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
