# Generated by Django 2.2.16 on 2022-04-09 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220409_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('a390dc14-3331-4602-9eda-ee61edd9c3a2'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
