# Generated by Django 2.2.16 on 2022-04-09 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220409_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('44ac637c-2f99-45fd-9509-e1ec70e6d83e'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
