# Generated by Django 2.2.16 on 2022-04-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220409_1540'),
        ('users', '0006_auto_20220409_1549'),
    ]

    operations = [
    ]
