# Generated by Django 2.2.16 on 2022-04-09 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20220409_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('be55ad21-41c2-4141-a418-2144c24411c7'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
