# Generated by Django 2.2.16 on 2022-04-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220403_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='confirmation_code',
        ),
    ]
