# Generated by Django 2.2.16 on 2022-04-07 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220407_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('afb2a6b5-43cc-45de-b31d-f85e6a4c0530'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
