# Generated by Django 2.2.16 on 2022-04-07 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220407_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('587726fd-1879-46a1-aad8-e644d90d958e'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
