# Generated by Django 2.2.16 on 2022-04-08 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220408_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default=uuid.UUID('10c67d83-3ae5-47e6-8ddf-35cde5aefe15'), max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
